version: '3.7'

services:

  mysql:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./config/api/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=goose
      - MYSQL_USER=goose
      - MYSQL_PASSWORD=1234

  api:
    image: redgoose/goose-api
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./config/api/nginx.conf:/etc/nginx/nginx.conf
      - ./config/api/.env:/goose/.env
      - ./config/api/data:/goose/data
      - ./config/api/data/log-nginx:/var/log/nginx
    links:
      - mysql:mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "7999:80"
    environment:
      - PMA_USER=goose
      - PMA_PASSWORD=1234 # mysql root password
      - PHP_UPLOAD_MAX_FILESIZE=100MB
