version: '3.7'

services:

  mysql:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=goose
      - MYSQL_USER=goose
      - MYSQL_PASSWORD=1234

  api:
    image: redgoose/goose-api
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./data/api/nginx.conf:/etc/nginx/nginx.conf
      - ./data/api/.env:/goose/.env
      - ./data/api/upload:/goose/data/upload
      - ./data/api/log-nginx:/var/log/nginx

  manager:
    build:
      context: ./data
      dockerfile: Dockerfile-manager
    ports:
      - "8001:3000"

  app:
    build:
      context: ./data
      dockerfile: Dockerfile-app
    ports:
      - "8002:3000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8003:80"
    environment:
      - PMA_HOST=mysql
      - PHP_UPLOAD_MAX_FILESIZE=100MB
#      - PMA_USER=
#      - PMA_PASSWORD=
    links:
      - mysql:mysql
