version: '3.7'

services:

  mysql:
    container_name: goose-mysql
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=goose
      - MYSQL_USER=goose
      - MYSQL_PASSWORD=1234

  api:
    container_name: goose-api
    image: redgoose/goose-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data/api/nginx.conf:/etc/nginx/nginx.conf
      - ./data/api/.env:/goose/.env
      - ./data/api/upload:/goose/data/upload
      - ./data/api/log-nginx:/var/log/nginx

  manager:
    container_name: goose-manager
    build:
      context: ./data
      dockerfile: Dockerfile-manager
    ports:
      - "8001:8001"
#    links:
#      - api

#  app:
#    container_name: goose-app
#    build:
#      context: ./data
#      dockerfile: Dockerfile-app
#    ports:
#      - "8002:8002"

#  phpmyadmin:
#    container_name: goose-myadmin
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8003:80"
#    environment:
#      - PMA_HOST=mysql
#      - PHP_UPLOAD_MAX_FILESIZE=100MB
##      - PMA_USER=
##      - PMA_PASSWORD=
#    links:
#      - mysql:mysql
