FROM node:11.1-alpine

RUN apk update && apk upgrade && apk add git

RUN git clone -b gallery https://github.com/redgoose-dev/goose-app.git

WORKDIR goose-app

RUN npm install

ENV HOST 0.0.0.0
ENV PORT 8002

RUN mkdir user

COPY app/env.js user/
COPY app/env.scss user/
COPY app/ico-logo.png static/
COPY app/img-error.png static/

RUN npm run build

EXPOSE 8002

CMD ["npm", "run", "start"]