FROM ubuntu:18.04
MAINTAINER redgoose <scripter@me.com>

RUN apt-get update

# install nginx
RUN apt-get -y install nginx

# install php
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y install php7.2

# install composer
RUN apt-get -y install openssl ca-certificates
RUN php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN chmod +x composer.phar
RUN mv composer.phar /usr/local/bin/composer

RUN echo "==== COMPLETE PROCESS ===="

EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]
